# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventNames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'event_names',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.EventNames')),
            ],
            options={
                'db_table': 'goals',
            },
        ),
        migrations.CreateModel(
            name='Investigators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('baptismal_date', models.DateField()),
            ],
            options={
                'db_table': 'investigators',
            },
        ),
        migrations.CreateModel(
            name='Missionaries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'missionaries',
            },
        ),
        migrations.CreateModel(
            name='Stakes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'stakes',
            },
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('stake_key', models.ForeignKey(db_column='stake_key', on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.Stakes')),
            ],
            options={
                'db_table': 'wards',
            },
        ),
        migrations.AddField(
            model_name='missionaries',
            name='ward',
            field=models.ForeignKey(db_column='ward', on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.Wards'),
        ),
        migrations.AddField(
            model_name='investigators',
            name='ward',
            field=models.ForeignKey(db_column='ward', on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.Wards'),
        ),
        migrations.AddField(
            model_name='goals',
            name='ward',
            field=models.ForeignKey(db_column='ward', on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.Wards'),
        ),
        migrations.AddField(
            model_name='events',
            name='investigator',
            field=models.ForeignKey(db_column='investigator', on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.Investigators'),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.EventNames'),
        ),
    ]
