# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventPossibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'event_possibility',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('event_possibility_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.EventPossibility')),
            ],
            options={
                'db_table': 'goal',
            },
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('baptismal_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investigator',
            },
        ),
        migrations.CreateModel(
            name='Missionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'missionary',
            },
        ),
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'stake',
            },
        ),
        migrations.CreateModel(
            name='StatusPossibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'status_possibility',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('stake_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.Stake')),
            ],
            options={
                'db_table': 'ward',
            },
        ),
        migrations.AddField(
            model_name='missionary',
            name='ward_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.Ward'),
        ),
        migrations.AddField(
            model_name='investigator',
            name='ward_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.Ward'),
        ),
        migrations.AddField(
            model_name='goal',
            name='ward_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.Ward'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_possibility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.EventPossibility'),
        ),
        migrations.AddField(
            model_name='event',
            name='investigator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KeyIndicators.Investigator'),
        ),
    ]
