# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeyIndicators', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='eventpossibility',
            table=None,
        ),
        migrations.AlterModelTable(
            name='goal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='investigator',
            table=None,
        ),
        migrations.AlterModelTable(
            name='missionary',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stake',
            table=None,
        ),
        migrations.AlterModelTable(
            name='statuspossibility',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ward',
            table=None,
        ),
    ]
