# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeyIndicators', '0005_auto_20171129_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionary',
            name='ward',
        ),
        migrations.DeleteModel(
            name='Missionary',
        ),
    ]
